added time and fixed functions
OnlyDeniko/ImageProcessing pull request #2
Opened 2020-10-03 09:23 UTC by WolfCub15

2020-10-03 14:45 UTC, BlackLunx requested changes

2020-10-03 14:45 UTC, BlackLunx commented on Laba1/opencs-test/opencs-test/opencs-test.cpp
> +	return ans / N;
До этого неправильно работало, брались первые 8 байт(так как double - 8 байт) типа данных Vec3b, а что там занимает эти 8 байт неизвестно)

2020-10-03 14:45 UTC, BlackLunx commented on Laba1/opencs-test/opencs-test/opencs-test.cpp
> +	return input * val;
Все попиксельные форы лучше бы заменить на матричные операции, а если не получается, то использовать 
`mat.forEach<type>([](type &x, const int* pos){}` 
тогда в лямбде x - элемент матрицы, а pos[0], pos[1] - позиция элемента
Это работает быстрее, чем двойной фор, потому что он распараллелен

2020-10-05 09:35 UTC, OnlyDeniko requested changes

2020-10-05 09:35 UTC, OnlyDeniko commented on Laba1/opencs-test/opencs-test/opencs-test.cpp
> +		if (h >= 60 && h < 120)		kek = Vec3d(0, C, X);
Мне кажется название kek для переменной не отображает сути использования этой переменной. Измени, пожалуйста

2020-10-05 09:48 UTC, OnlyDeniko approved these changes

2020-10-05 12:03 UTC, BlackLunx approved these changes
Так-то все норм, но однобуквенные переменные лучше не юзать

2020-10-05 12:24 UTC, merged